### PR TITLE
Apollo 66

### PR DESCRIPTION
**Pull request by DuncanZauss**
Hi @svenkreiss and @bertoni9 ,
I have added the 66 kp version of apollocar. There is a new cli flag to switch between the two versions. Also, the apollocar module is now using the COCO dataloader.

### CODE REVIEW

**Comment by svenkreiss** [comment]
Thanks @DuncanZauss . Can you check the logs of the tests and see whether you can fix this? Thanks.

**Comment by DuncanZauss** [comment]
Hi @svenkreiss, I have fixed the parts that were not accepted by pylint. As you can see in the test logs, one test on the CIFAR dataset is not passed on ubuntu with python 3.8. Any hint on what I can do about that?

**Comment by svenkreiss** [comment]
Thanks for checking and fixing. The cifar10 error is unclear to me. Maybe this is just spurious. Everything else looks good to go. Can you just remove the gif files you committed? They are too large for version control (each over 5MB). We will move the readme to a page in the guide and there we will generate the gif's on the fly. They will then be added to gh-pages which is an orphaned branch that doesn't accumulate history.

**Comment by DuncanZauss** [comment]
Thanks for the feedback. I have removed the gifs. The problem with CIFAR 10 on python 3.8 seems to persist. Do you think it is still okay to merge?

**Comment by svenkreiss** [comment]
Thanks!

**Pull request merged**
