### PR TITLE
--save-all

### PR DESCRIPTION
**Pull request by svenkreiss**
This saves all the plots that would not otherwise be saved into a directory. So it creates a folder `all-images` (or something you specify with `--save-all`) and then enumerates all plots `0001.png`, `0002.png`, ...

I'd be curious to hear your inputs in the comments below @george-adaimi @bertoni9 @gondimjoaom as this is intended for your remote and headless setup.

### CODE REVIEW

**Comment by bertoni9** [comment]
It works on my side and I like it a lot. 
I would also add the --show (or --no-show) option to avoid showing figures if needed. For example, with the default Tkinter on matplotlib, you first need to close the current figure to move to the following one.

Lorenzo

**Comment by svenkreiss** [comment]
Oh, thanks @bertoni9 . Somehow I thought that would already happen. I thought the mechanism that is in `predict` extends to all plots. Obviously not. I'll look into generalizing that.

**Comment by svenkreiss** [comment]
Now this should work completely without GUI. 
You now have to specify `--show` (or `--save-all`) for every command, even for `openpifpaf.logs`.

**Comment by gondimjoaom** [comment]
this is going to be interesting for checking models' outputs on videos "on the go" and to check how openpifpaf deals post processing for returned points. Will take a look on that! Thanks!

**Comment by svenkreiss** [comment]
I am going to merge this into dev now because I need it for something else, but feel free to add comments here or open an issue related to --save-all if anything comes up.

**Pull request merged**
