### PR TITLE
add wheels for macos-11.0

### PR DESCRIPTION
**Pull request by svenkreiss**

### CODE REVIEW

**Comment by svenkreiss** [comment]
Tests pass but this isn't right for macos-11.0. The wheels that are built are tagged with `macosx_10_9` while I would expect `macosx_11_0` according to latest home-brew Python and `pip debug`.

**Comment by svenkreiss** [comment]
Waiting for this: https://github.com/pypa/pip/issues/8936

**Comment by pradyunsg** [comment]
Well, pip 20.3 has been released. But, it's the download-install part of the build-publish-download-install flow.

I'd imagine the issue is in the build parts here. And, PyPI is probably not ready for the publish bits either.

**Comment by svenkreiss** [comment]
cibuildwheel is tracking this issue here: https://github.com/joerick/cibuildwheel/issues/473

**Comment by Czaki** [comment]
cibuildwheel build wheels using self-installed python, so its no matter that you install python from brew. 
cibuildwheel needs a python universal installer from python.org to build a wheel for macOS 11.0 ARM. 

Most probably they will be still tagged `macos_10_9_universal` to point that x86_64 part of the wheel will work on macos in version at least 10.9.

**Pull request closed without merging**
