### PR TITLE
Make resnet50 backbone convertable to tensorRT by using torch2trt

### PR DESCRIPTION
**Pull request by thancaocuong**
* Change inplace ops by torch.op to compatible with torch2trt converter
* Todo: Implement PixelShuffle Layer for converting PixelShuffle backbone, C++ implementation, deepstream gst plugin for Nvidia edge devices.

### CODE REVIEW

**Comment by svenkreiss** [comment]
Hi @thancaocuong , this looks great. Thanks! Waiting for your CLA. Let me know if you have any concerns.

**Comment by svenkreiss** [comment]
@cla-bot check

**Review by svenkreiss — APPROVED** [review]
Thanks!

**Comment by svenkreiss** [comment]
By the way @thancaocuong , impressive Todo list. Looking forward to your progress. Always feel free to share updates and questions here in issues and PRs.

**Comment by thancaocuong** [comment]
@svenkreiss they are still inprogress. I will start with TensorRT C++ inference, but first I need to understand how c++ source for decoding works (expected inputs for decoder),...

**Pull request merged**
