### PR TITLE
Dynamic batch support

### PR DESCRIPTION
**Pull request by ganler**
> Legacy: Dynamic batch is not supported that you can only use batch_size=1 otherwise inference libs like TensorRT or ONNXRuntime will report errors.

For the ONNX exporter, I find ways to enable the availability of dynamic batch.

Cause: Some Numpy operations are unexportable that need to be rewritten by torch codes;
Solution: Re-written by torch codes. To be more specific, re-write: [np.flip(np.indices(...))]

**Help**: @svenkreiss  Now ONNX Runtime and TensorRT can run the models, but I didn't implement the post-processing codes that cold you take a look at if the results are correct when the batch size != 1? (Cuz I am new to pifpaf codes....)

Verified:

1. ONNX Runtime can adapt to different batch size;
2. TensorRT can adapt to different batch size;
3. OpenPifPaf original codes can run correctly;

Screenshot_20201119_182908

### CODE REVIEW

**Comment by svenkreiss** [comment]
Hi @ganler , thanks a lot for looking into this. Do you mind sending me a CLA (what the bot mentioned above)?
To have this tested immediately, it would be great if you could make this pull request against the dev branch. There is a test (but only in dev) that checks that the model is working as before. Let me know if you have any questions/concerns about this.

**Comment by ganler** [comment]
@svenkreiss Sure, plz check your email.

**Comment by svenkreiss** [comment]
Thanks @ganler ! Something went wrong with the unit tests. We recently had to switch to GitHub Actions and there was a misconfiguration. Can you merge the dev branch into your branch again? That updates the workflow files in your branch and hopefully will trigger the full test suite.

**Comment by ganler** [comment]
@svenkreiss Done!

**Review by svenkreiss — APPROVED** [review]
Looks great. Thanks!

**Pull request merged**
