### PR TITLE
WIP: sample C++ postprocessing code

### PR DESCRIPTION
**Pull request by mdenna-nviso**

### CODE REVIEW

**Comment by svenkreiss** [comment]
Awesome! Had a brief look and it looks great. 

I will fix the cla-bot.

**Comment by svenkreiss** [comment]
@cla-bot check

**Comment by svenkreiss** [comment]
What are the next steps with this? The code looks great.

You are building one binary? Whatever is easiest for your cmake setup, lets get that in to produce a minimal C example binary.

**Comment by mdenna-nviso** [comment]
> What are the next steps with this? The code looks great.
> 
> You are building one binary? Whatever is easiest for your cmake setup, lets get that in to produce a minimal C example binary.

maybe we can add a sample main that calls this postprocess methos with some constant inputs? would that be enough?

**Comment by mdenna-nviso** [comment]
> > What are the next steps with this? The code looks great.
> > You are building one binary? Whatever is easiest for your cmake setup, lets get that in to produce a minimal C example binary.
> 
> maybe we can add a sample main that calls this postprocess methos with some constant inputs? would that be enough?

I added a cmake + dummy main that calls the decoder with null input. This is just to verify that the code compiles.
Of course a better example would later include the possibility to pass data in input via command line parameters or files, and printout the result. Also it would be nice to have a python wrapper so that the decoder can be called from python.

**Comment by mdenna-nviso** [comment]
Do you think this is good enough as a starting point?

**Comment by svenkreiss** [comment]
Yes, I think this is a good starting point.

At some point, we need to get it to a level where there is a minimal, self-contained test case. The example should produce some actual annotations and we should have a test for the number of annotations. Instead of initializing with zeros, can you initialize with an example?

**Comment by mdenna-nviso** [comment]
Yes, this sample code could be improved by adding real data. I could run the network 0.8 and in some way collect the net outputs and the post-processed result. Not sure it is worth the effort as 0.8 is now obsolete, unless this could be helpful in porting the C++ code to the new version for 0.11. What do you think?

**Comment by svenkreiss** [comment]
Yes, I think having a working example before starting the port is valuable.

**Comment by mdenna-nviso** [comment]
> Yes, I think having a working example before starting the port is valuable.

Hi Sven, I added some sample input/output data, let me know if good enough..
Thanks
-m

**Comment by svenkreiss** [comment]
Looks good to me. Thanks!

Ready to merge?

**Comment by mdenna-nviso** [comment]
> Looks good to me. Thanks!
> 
> Ready to merge?

Yes for me. The sample code builds and the result matches what is expected

**Pull request merged**
